FROM python:3.10-slim

WORKDIR /streamlit

COPY requirements.streamlit.txt .
RUN pip install --no-cache-dir -r requirements.streamlit.txt

COPY streamlit/streamlit_app.py .

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.enableCORS=false"]
